version: '3.3'
services:
  tyk-dashboard-sso:
    image: tykio/tyk-dashboard:${DASHBOARD_SSO_VERSION:-latest}
    ports:
      - 3001:3000
    networks:
      - tyk
    volumes:
      - ./deployments/tyk/volumes/tyk-dashboard/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
    environment:
      - TYK_DB_LICENSEKEY=${DASHBOARD_LICENCE:?Please set DASHBOARD_LICENCE in .env}
      - TYK_DB_SSOCUSTOMLOGINURL=http://localhost:3010/auth/tyk-dashboard/openid-connect
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED:-0}
      - TYK_LOGLEVEL=${TYK_LOGLEVEL:-info}
    depends_on:
      - tyk-identity-broker
      - tyk-mongo
      - tyk-redis
  tyk-identity-broker:
    image: tykio/tyk-identity-broker:${TIB_VERSION:-latest}
    networks:
      - tyk
    ports:
      - 3010:3010
    environment:
      - SESSION_SECRET=${TIB_SESSION_SECRET:-12345}
      - TYK_LOGLEVEL=${TYK_LOGLEVEL:-info}
    volumes:
      - ./deployments/sso/volumes/tyk-identity-broker/tib.conf:/opt/tyk-identity-broker/tib.conf