version: '3.3'
services:
  tyk-dashboard-sso:
    image: tykio/tyk-dashboard:v3.0.1
    ports:
      - 3001:3000
    networks:
      - tyk
    volumes:
      - ./deployments/tyk/volumes/tyk-dashboard/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
    environment:
      - TYK_DB_LICENSEKEY=${DASHBOARD_LICENCE}
      - TYK_DB_SSOCUSTOMLOGINURL=http://localhost:3010/auth/tyk-dashboard/openid-connect
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED}
    depends_on:
      - tyk-identity-broker
      - tyk-mongo
      - tyk-redis
  tyk-identity-broker:
    image: tykio/tyk-identity-broker:v1.0.0
    networks:
      - tyk
    ports:
      - 3010:3010
    environment:
      - SESSION_SECRET=12345
    volumes:
      - ./deployments/sso/volumes/tyk-identity-broker/tib.conf:/opt/tyk-identity-broker/tib.conf