version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:2.319.2-lts-alpine
    ports:
      - 8070:8080
    networks:
      - tyk
    volumes:
      - ./deployments/cicd/volumes/jenkins/plugins.txt:/usr/share/jenkins/plugins.txt
      - ./deployments/cicd/volumes/jenkins/plugins:/usr/share/jenkins/ref/plugins
  gitea:
    image: gitea/gitea:1.11.5
    environment:
      - HTTP_PORT=13000
    ports:
      - "13000:13000"
      - "127.0.0.1:2222:22"
    networks:
      - tyk
    volumes:
      - ./deployments/cicd/volumes/gitea/gitea-dump.zip:/data/gitea-dump.zip
      - ./deployments/cicd/volumes/gitea/restore.sh:/data/restore.sh