version: '3.3'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:latest
    ports:
      - "3000:3000"
      - "5000:5000"
    networks:
      - tyk
    volumes:
      - ./volumes/tyk-dashboard/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
    environment:
      - TYK_DB_LICENSEKEY=${DASHBOARD_LICENCE}
    depends_on:
      - tyk-redis
      - tyk-mongo
      - tyk-identity-broker
  tyk-dashboard-sso:
    image: tykio/tyk-dashboard:latest
    ports:
      - "3001:3000"
      - "5001:5000"
    networks:
      - tyk
    volumes:
      - ./volumes/tyk-dashboard/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
    environment:
      - TYK_DB_LICENSEKEY=${DASHBOARD_LICENCE}
      - TYK_DB_SSOCUSTOMLOGINURL=http://localhost:3010/auth/tyk-dashboard/openid-connect
    depends_on:
      - tyk-redis
      - tyk-mongo
      - tyk-identity-broker
  tyk-gateway:
    image: tykio/tyk-gateway:latest
    ports:
      - "8080:8080"
    networks:
      - tyk
    volumes:
      - ./volumes/tyk-gateway/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./volumes/tyk-gateway/middleware:/opt/tyk-gateway/middleware
    depends_on:
      - tyk-redis
  tyk-gateway-tls:
    image: tykio/tyk-gateway:latest
    ports:
      - "8081:8080"
    networks:
      - tyk
    volumes:
      - ./volumes/tyk-gateway/tyk-tls.conf:/opt/tyk-gateway/tyk.conf
      - ./volumes/tyk-gateway/middleware:/opt/tyk-gateway/middleware
      - ./volumes/tyk-gateway/certificates:/opt/tyk-gateway/certificates
    environment:
      - TYK_GW
    depends_on:
      - tyk-redis
  tyk-pump:
    image: tykio/tyk-pump-docker-pub:latest
    networks:
      - tyk
    volumes:
      - ./volumes/tyk-pump/pump.conf:/opt/tyk-pump/pump.conf
    depends_on:
      - tyk-redis
      - tyk-mongo
      - tyk-gateway
      - elasticsearch
  tyk-redis:
    image: redis
    volumes:
      - redis-data:/data
    networks:
      - tyk
  tyk-mongo:
    image: mongo:3.2
    command: ["mongod", "--smallfiles"]
    volumes:
      - mongo-data:/data/db
    networks:
      - tyk
  httpbin:
    image: kennethreitz/httpbin
    networks:
      - tyk
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.8
    networks:
      - tyk
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    environment:
      - discovery.type=single-node
    networks:
      - tyk
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  tyk-identity-broker:
    image: tykio/tyk-identity-broker:latest
    networks:
      - tyk
    ports:
      - 3010:3010
    environment:
      - SESSION_SECRET=12345
    volumes:
      - "./volumes/tyk-identity-broker/tib.conf:/opt/tyk-identity-broker/tib.conf"
  jenkins:
    image: jenkins/jenkins:lts-slim
    ports:
      - "8070:8080"
    networks:
      - tyk
    volumes:
      - jenkins-data:/var/jenkins_home
  e2-tyk-dashboard:
    image: tykio/tyk-dashboard:latest
    ports:
      - "3002:3000"
      - "5002:5000"
    networks:
      - tyk
    volumes:
      - ./volumes/tyk-dashboard/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
    environment:
      - TYK_DB_LICENSEKEY=${DASHBOARD_LICENCE}
      - TYK_DB_MONGOURL=mongodb://e2-tyk-mongo:27017/tyk_analytics
      - TYK_DB_TYKAPICONFIG_HOST=http://e2-tyk-gateway
      - TYK_DB_HOSTCONFIG_OVERRIDEHOSTNAME=localhost:8085
    depends_on:
      - e2-tyk-redis
      - e2-tyk-mongo
  e2-tyk-mongo:
    image: mongo:3.2
    command: ["mongod", "--smallfiles"]
    volumes:
      - e2-mongo-data:/data/db
    networks:
      - tyk
  e2-tyk-redis:
    image: redis
    volumes:
      - e2-redis-data:/data
    networks:
      - tyk
  e2-tyk-gateway:
    image: tykio/tyk-gateway:latest
    ports:
      - "8085:8080"
    networks:
      - tyk
    volumes:
      - ./volumes/tyk-gateway/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./volumes/tyk-gateway/middleware:/opt/tyk-gateway/middleware
    environment:
      - TYK_GW_POLICIES_POLICYCONNECTIONSTRING=http://e2-tyk-dashboard:3000
      - TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING=http://e2-tyk-dashboard:3000
      - TYK_GW_STORAGE_HOST=e2-tyk-redis
    depends_on:
      - e2-tyk-redis
  e2-tyk-pump:
    image: tykio/tyk-pump-docker-pub:latest
    networks:
      - tyk
    volumes:
      - ./volumes/tyk-pump/e2-pump.conf:/opt/tyk-pump/pump.conf
    depends_on:
      - e2-tyk-redis
      - e2-tyk-mongo
      - e2-tyk-gateway
      

volumes:
  redis-data:
  mongo-data:
  e2-redis-data:
  e2-mongo-data:
  elasticsearch-data:
  jenkins-data:

networks:
  tyk: