version: '3.3'
services:
  jenkins:
    image: jenkins/jenkins:lts-alpine
    ports:
      - "8070:8080"
    networks:
      - tyk
    volumes:
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-data: