version: '3.3'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:latest
    ports:
      - "3000:3000"
      - "5000:5000"
    networks:
      - tyk
    volumes:
      - ./volumes/tyk-dashboard/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
    environment:
      - TYK_DB_LICENSEKEY=${DASHBOARD_LICENCE}
    depends_on:
      - tyk-redis
      - tyk-mongo
      - tyk-identity-broker
  tyk-dashboard-sso:
    image: tykio/tyk-dashboard:latest
    ports:
      - "3001:3000"
      - "5001:5000"
    networks:
      - tyk
    volumes:
      - ./volumes/tyk-dashboard/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
    environment:
      - TYK_DB_LICENSEKEY=${DASHBOARD_LICENCE}
      - TYK_DB_SSOCUSTOMLOGINURL=http://localhost:3010/auth/tyk-dashboard/openid-connect
    depends_on:
      - tyk-redis
      - tyk-mongo
      - tyk-identity-broker
  tyk-gateway:
    image: tykio/tyk-gateway:latest
    ports:
      - "8080:8080"
    networks:
      - tyk
    volumes:
      - ./volumes/tyk-gateway/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./volumes/tyk-gateway/middleware:/opt/tyk-gateway/middleware
    depends_on:
      - tyk-redis
  tyk-gateway-tls:
    image: tykio/tyk-gateway:latest
    ports:
      - "8081:8080"
    networks:
      - tyk
    volumes:
      - ./volumes/tyk-gateway/tyk-tls.conf:/opt/tyk-gateway/tyk.conf
      - ./volumes/tyk-gateway/middleware:/opt/tyk-gateway/middleware
      - ./volumes/tyk-gateway/certificates:/opt/tyk-gateway/certificates
    environment:
      - TYK_GW
    depends_on:
      - tyk-redis
  tyk-pump:
    image: tykio/tyk-pump-docker-pub:latest
    networks:
      - tyk
    volumes:
      - ./volumes/tyk-pump/pump.conf:/opt/tyk-pump/pump.conf
    depends_on:
      - tyk-redis
      - tyk-mongo
      - tyk-gateway
  tyk-redis:
    image: redis
    volumes:
      - redis-data:/data
    networks:
      - tyk
  tyk-mongo:
    image: mongo:3.2
    command: ["mongod", "--smallfiles"]
    volumes:
      - mongo-data:/data/db
    networks:
      - tyk
  tyk-identity-broker:
    image: tykio/tyk-identity-broker:latest
    networks:
      - tyk
    ports:
      - 3010:3010
    environment:
      - SESSION_SECRET=12345
    volumes:
      - "./volumes/tyk-identity-broker/tib.conf:/opt/tyk-identity-broker/tib.conf"
  httpbin:
    image: kennethreitz/httpbin
    networks:
        - tyk
  swagger-petstore:
    image: swaggerapi/petstore:latest
    networks:
      - tyk
    environment:
      - SWAGGER_HOST=http://swagger-petstore:8080
      - SWAGGER_URL=http://localhost:8080/swagger-petstore

volumes:
  redis-data:
  mongo-data:

networks:
  tyk: