version: '3.3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.8
    networks:
      - tyk
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    environment:
      - discovery.type=single-node
    networks:
      - tyk
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

volumes:
  elasticsearch-data:

networks:
  tyk: