version: '3.3'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:latest
    ports:
      - "3000:3000"
    networks:
      - tyk
    volumes:
      - tyk/volumes/tyk-dashboard/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
    environment:
      - TYK_DB_LICENSEKEY=${DASHBOARD_LICENCE}
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED}
    depends_on:
      - tyk-redis
      - tyk-mongo
  tyk-gateway:
    image: tykio/tyk-gateway:latest
    ports:
      - "8080:8080"
    networks:
      - tyk
    environment:
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED}
      - TYK_GW_TRACER_ENABLED=${TRACING_ENABLED}
    volumes:
      - tyk/volumes/tyk-gateway/tyk.conf:/opt/tyk-gateway/tyk.conf
      - tyk/volumes/tyk-gateway/middleware:/opt/tyk-gateway/middleware
    depends_on:
      - tyk-redis
  tyk-pump:
    image: tykio/tyk-pump-docker-pub:latest
    networks:
      - tyk
    volumes:
      - tyk/volumes/tyk-pump/pump.conf:/opt/tyk-pump/pump.conf
    environment:
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED}
    depends_on:
      - tyk-redis
      - tyk-mongo
  tyk-redis:
    image: redis
    volumes:
      - tyk-redis-data:/data
    networks:
      - tyk
  tyk-mongo:
    image: mongo:3.2
    command: ["mongod", "--smallfiles"]
    volumes:
      - tyk-mongo-data:/data/db
    networks:
      - tyk
  httpbin:
    image: kennethreitz/httpbin
    networks:
      - tyk
  swagger-petstore:
    image: swaggerapi/petstore:latest
    networks:
      - tyk
    environment:
      - SWAGGER_HOST=http://swagger-petstore:8080
      - SWAGGER_URL=http://localhost:8080/swagger-petstore
    
volumes:
  tyk-redis-data:
  tyk-mongo-data:

networks:
  tyk: