version: '3.3'
services:
  tyk2-dashboard:
    image: tykio/tyk-dashboard:v3.0.0
    ports:
      - 3002:3000
    networks:
      - tyk
    volumes:
      - ./deployments/tyk/volumes/tyk-dashboard/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
    environment:
      - TYK_DB_LICENSEKEY=${DASHBOARD_LICENCE}
      - TYK_DB_MONGOURL=mongodb://tyk2-mongo:27017/tyk_analytics
      - TYK_DB_REDISHOST=tyk2-redis
      - TYK_DB_TYKAPICONFIG_HOST=http://tyk2-gateway
      - TYK_DB_HOSTCONFIG_OVERRIDEHOSTNAME=localhost:8085
    depends_on:
      - tyk2-redis
      - tyk2-mongo
  tyk2-gateway:
    image: tykio/tyk-gateway:v3.0.0
    ports:
      - 8085:8080
    networks:
      - tyk
    volumes:
      - ./deployments/tyk/volumes/tyk-gateway/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./deployments/tyk/volumes/tyk-gateway/middleware:/opt/tyk-gateway/middleware
    environment:
      - TYK_GW_POLICIES_POLICYCONNECTIONSTRING=http://tyk2-dashboard:3000
      - TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING=http://tyk2-dashboard:3000
      - TYK_GW_STORAGE_HOST=tyk2-redis
    depends_on:
      - tyk2-redis
  tyk2-pump:
    image: tykio/tyk-pump-docker-pub:v0.8.5
    networks:
      - tyk
    volumes:
      - ./deployments/tyk2/volumes/tyk-pump/pump.conf:/opt/tyk-pump/pump.conf
    depends_on:
      - tyk2-redis
      - tyk2-mongo
      - tyk2-gateway
  tyk2-mongo:
    image: mongo:3.2
    command: ["mongod", "--smallfiles"]
    volumes:
      - tyk2-mongo-data:/data/db
    networks:
      - tyk
  tyk2-redis:
    image: redis
    volumes:
      - tyk2-redis-data:/data
    networks:
      - tyk
    
volumes:
  tyk2-redis-data:
  tyk2-mongo-data: