version: '3.3'
services:
  tyk-portal:
    image: tykio/portal:v0.0.1-rc13
    networks:
      - tyk
    env_file:
      - .env
    ports:
      - 3100:3001
    entrypoint: /opt/portal/dev-portal
    volumes:
      - ./deployments/portal/volumes/database/portal.db:/opt/portal/portal.db
      - ./deployments/portal/volumes/assets/:/opt/portal/public/system/products/