version: '3.3'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:${DASHBOARD_VERSION:-latest}
    ports:
      - 3000:3000
    networks:
      - tyk
    volumes:
      - ./deployments/tyk/volumes/tyk-dashboard/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
      - ./deployments/tyk/volumes/tyk-dashboard/private-key.pem:/opt/tyk-dashboard/private-key.pem
    environment:
      - TYK_DB_LICENSEKEY=${DASHBOARD_LICENCE:?Dashboard licence missing from Docker environment file .env. Review The Getting Started steps in README.md.}  
      - TYK_LOGLEVEL=${DASHBOARD_LOGLEVEL:-info}
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED:-0}
    depends_on:
      - tyk-redis
      - tyk-mongo
  tyk-gateway:
    image: tykio/tyk-gateway:${GATEWAY_VERSION:-latest}
    ports:
      - 8080:8080
    networks:
      - tyk
    environment:
      - TYK_LOGLEVEL=${GATEWAY_LOGLEVEL:-info}
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED:-0}
      - TYK_GW_TRACER_ENABLED=${TRACING_ENABLED:-0}
    volumes:
      - ./deployments/tyk/volumes/tyk-gateway/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./deployments/tyk/volumes/tyk-gateway/certs:/opt/tyk-gateway/certs
      - ./deployments/tyk/volumes/tyk-gateway/middleware:/opt/tyk-gateway/middleware
    depends_on:
      - tyk-redis
  tyk-gateway-2:
    image: tykio/tyk-gateway:${GATEWAY2_VERSION:-latest}
    ports:
      - 8081:8080
    networks:
      - tyk
    environment:
      - TYK_LOGLEVEL=${GATEWAY2_LOGLEVEL:-info}
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED:-0}
      - TYK_GW_TRACER_ENABLED=${TRACING_ENABLED:-0}
    volumes:
      - ./deployments/tyk/volumes/tyk-gateway/tyk-2.conf:/opt/tyk-gateway/tyk.conf
      - ./deployments/tyk/volumes/tyk-gateway/certs:/opt/tyk-gateway/certs
      - ./deployments/tyk/volumes/tyk-gateway/middleware:/opt/tyk-gateway/middleware
    depends_on:
      - tyk-redis
      - tyk-gateway
  tyk-pump:
    image: tykio/tyk-pump-docker-pub:${PUMP_VERSION:-latest}
    networks:
      - tyk
    volumes:
      - ./deployments/tyk/volumes/tyk-pump/pump.conf:/opt/tyk-pump/pump.conf
    environment:
      - TYK_INSTRUMENTATION=${INSTRUMENTATION_ENABLED:?0}
      - TYK_LOGLEVEL=${PUMP_TYK_LOGLEVEL:-info}
    depends_on:
      - tyk-redis
      - tyk-mongo
  tyk-redis:
    image: redis
    ports:
    - "6379:6379"
    volumes:
      - tyk-redis-data:/data
    networks:
      - tyk
  tyk-mongo:
    image: mongo:3.2
    command: ["mongod", "--smallfiles"]
    ports:
    - "27017:27017"
    volumes:
      - tyk-mongo-data:/data/db
    networks:
      - tyk
  httpbin:
    image: kennethreitz/httpbin
    networks:
      tyk:
        aliases:
          - httpbin2
  swagger-petstore:
    image: swaggerapi/petstore:latest
    networks:
      - tyk
    environment:
      - SWAGGER_HOST=http://swagger-petstore:8080
      - SWAGGER_URL=http://localhost:8080/swagger-petstore

volumes:
  tyk-redis-data:
  tyk-mongo-data:

networks:
  tyk:

