version: '3.3'
services:
  waf:
    image: owasp/modsecurity-crs:v3.0
    networks:
      - tyk
    ports:
      - "8500:80"
    environment:
      - PARANOIA=1
    deploy:
      restart_policy:
        condition: any