name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Set up environment
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ".env"
          FILE_DATA: "DASHBOARD_LICENCE=${{ secrets.DASH_LICENSE }}"
      - run: sudo ./scripts/update-hosts.sh
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Bootstrap Tyk
        run: |
          sudo ./up.sh
      - name: Run Postman tests
        run: |
          sudo ./scripts/test.sh
      - run: echo "🍏 This job's status is ${{ job.status }}."
