name: Tyk Demo API Tests
on: [push]
jobs:
  Tyk-Demo-Api-Tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Create environment file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: ".env"
          FILE_DATA: "DASHBOARD_LICENCE=${{ secrets.DASH_LICENSE }}"
      - name: Update hosts
        run: sudo ./scripts/update-hosts.sh
      - name: Bootstrap Tyk
        run: sudo ./up.sh
      - name: Store bootstrap log
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: bootstrap-log
          path: bootstrap.log
      - name: Show bootstrap log
        if: success() || failure()
        run: cat bootstrap.log
      - name: Run Postman tests
        run: sudo ./scripts/test-all.sh
      - run: echo "🍏 This job's status is ${{ job.status }}."
